### ISSUE TITLE
Room user bulk update / delete

### ISSUE THREAD

**Issue by SamuelWei** [THM-Health/PILOS#211]
**Is your feature request related to a problem? Please describe.**
If multiple room users should be removed at the end of a semester or the roles changed, every user has to be manually deleted or changed.

**Describe the solution you'd like**
Add checkboxes to the room users list and buttons to mass remove and mass edit. Also add button to toogle the selection of all room users. Add confirm modal before executing the action.

**Describe alternatives you've considered**
*none*

**Additional context**
See mockup
![image](https://user-images.githubusercontent.com/4281791/162919614-30a4f73d-38e0-4e26-9e77-ea2336d66de4.png)

**TODO**

- [ ] Frontend: Show checkboxes based on permission
- [ ] Frontend: Show edit and remove button for selected members if at least one is selected, eg. Edit users (5), Delete users (5)
- [ ] Frontend: Add modal to confirm delete
- [ ] Frontend: Add modal to edit selected users, set new role
- [ ] Backend: Add new route for mass delete and mass edit
- [ ] Backend: Add validation for mass delete and mass edit
- [ ] Backend: Implement mass delete
- [ ] Backend: Implement mass edit
- [ ] Frontend: Add tests
- [ ] Backend: Add tests
