### ISSUE TITLE
Enable recordings

### ISSUE THREAD

**Issue by SamuelWei** [THM-Health/PILOS#31]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Add checkbox to room settings to allow recordings for a meeting. If true enforce agreement on joining of meeting.

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by SamuelWei** [comment]
**TODOs**

- [ ] Add checkbox to settings to record meeting
- [ ] Add checkbox to settings to record meeting on start
- [ ] Add message to user that meeting is beeing recorded before start/join (Enforce agreement)
- [ ] Add global setting to allow/disallow recordings
- [ ] Add setting to room types to allow/disallow recordings
- [ ] Add recording managment like Greenlight + Scalelite (shared volume) with permission check on recording access

**Comment by pritamnanda** [comment]
Really there wasn't any option for recording till Version 3.0.3?

I am exploring 3.0.3 version as V4 isn't yet released for production, but I can't see any option for Recording at all.

Can anyone please confirm if Version 3 has any Recording Option with any add-on or plugin or advanced configuration?

**Comment by SamuelWei** [comment]
@pritamnanda I can confirm, there is no recording prior to v4. V4-RC4 is already very good and we use it in production. The final release is delayed due to some minor bugs.

**Comment by pritamnanda** [comment]
@SamuelWei Thanks for your clarification. I tried to Install & configure but at the End it seems some configuration issue or bug, I am not sure.

![Screenshot 2024-09-21 191139](https://github.com/user-attachments/assets/90aa01c4-b5cf-4e50-b778-91077af0727e)
![Screenshot 2024-09-21 195403](https://github.com/user-attachments/assets/c5d1b413-44c5-46d8-af00-c52543705442)
![Screenshot 2024-09-21 195507](https://github.com/user-attachments/assets/0162e669-95d0-476e-bada-b55ff35e113a)

Can you please have a look if this is a familiar issue?

I have added the .env & docker-compose.yml properly, with Nginx , version pilos/pilos:4.0.0-RC.4

After docker compose up -d, I am stuck with this Error

Oops! An Error Occurred
The server returned a "400 Bad Request".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by SamuelWei** [comment]
I expect that the domain name your request comes from is invalid.
Please check the .env APP_URL and your reverse proxy settings

**Comment by pritamnanda** [comment]
Thanks for your quick response @SamuelWei 

I have added the Domain in .env, Configured Nginx with below server block only without any rate limiting

location / {
  proxy_pass          http://127.0.0.1:5000;
  proxy_set_header    X-Forwarded-Host $host;
  proxy_set_header    X-Forwarded-Port  $server_port;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_http_version  1.1;
}

Getting the Mentioned Error after Starting Docker Compose

After I stop Docker-compose getting standard Nginx 502 Bad Gateway

Just now I found that Pilos-Redis is using 6379/tcp, which is already being used by the Greenlight-Redis as I am trying to install on a Standalone BBB server where BBB & GL dashboard are already running.

I think this might be the issue.

By the way, If I still have to reach out to you, should I keep adding comments on this issue like this? I think this may lead to irrelevant search results for the community members.

Do you recommend creating a Fresh Issue for further discussion? Or do we have any other options?

Thanks
Pritam

**Comment by SamuelWei** [comment]
You could add a new discussion over here: https://github.com/THM-Health/PILOS/discussions/categories/q-a

**Comment by pritamnanda** [comment]
Thanks @SamuelWei for your quick response & guidance. My issue is resolved by adding TRUSTED_PROXIES=* in .env 

This is my last comment here regarding this. If it is possible you may delete these last few comments irrelevant to the Issue.

In future, I will create a new discussion over there or open an issue, if necessary.

Thanks again.
